### PR TITLE
Add tests for the current functionality

### PR DESCRIPTION
**Pull request by mrmlnc**
Changelog:
- Added tests for the current functionality
- Drop support Node.js v0.10.0 because npm v1 deprecated
- Added Travis.ci config ([temporarily available here](https://travis-ci.org/mrmlnc/gulp-directory-sync))

### CODE REVIEW

**Comment by mrmlnc** [comment]
Sorry, I'll return the support v0.10 in the morning.

**Comment by peteward44** [comment]
Thanks for this. Yes, i would like to retain 0.10 support as this is still quite common in many production environments

**Comment by peteward44** [comment]
Thanks for this. Yes, I would like to retain 0.10.x support, as this is still very common in many production environments.

**Comment by mrmlnc** [comment]
Oh, it was a long night :tada: (fun)

I finally found the time and corrected tests.

**Pull request merged**
